version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: room-db-container
    environment:
      MYSQL_DATABASE: 'room-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - room-network

  api:
    build: .
    container_name: room-api-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/room-db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - room-network

networks:
  room-network:
    driver: bridge

volumes:
  db_data: